### ISSUE TITLE
Rename `*.ql` files to `*.overpassql`

### ISSUE THREAD

**Issue by FloEdelmann** [osmlab/osm-landmarks#13]
`*.overpassql` is now the recommended file extension for Overpass QL: [OSM Wiki: Overpass QL § File extension](https://wiki.openstreetmap.org/wiki/Overpass_API/Overpass_QL#File_extension)
*(**Disclaimer:** I added that section after [some discussion](https://wiki.openstreetmap.org/wiki/Talk:Overpass_API/Overpass_QL#Recommended_file_extension?).)*

I propose to rename all Overpass QL files in this repo to `*.overpassql` for consistency.

Context: GitHub's syntax highlighting engine requires that 200 repositories use the same file extension before they consider supporting that syntax and file extension: https://github.com/github/linguist/issues/5890

**Comment by FloEdelmann** [comment]
@bkowshik Would a pull request be accepted?

**Comment by bkowshik-rapido** [comment]
👋  @FloEdelmann I am currently not maintaining this repository.

**Comment by FloEdelmann** [comment]
@bkowshik-rapido Since the PR would only rename some files and not change the behavior, would that be okay anyway? Or did you lose push permissions in this repository? If so, do you know who could merge PRs now?

**Comment by 1ec5** [comment]
Looks like I would be able to merge the PR for you.

Note that the OverpassQL file is being loaded by this line of code:

https://github.com/osmlab/osm-landmarks/blob/dac372106fd263dd506b2d3f7e05f77853bb221e/scripts/overpass-query.js#L22

Apart from that, I don’t think it’s being exported to downstream packages like [osm-compare](https://github.com/mapbox/osm-compare/).

**Comment by FloEdelmann** [comment]
@1ec5 Cool, I created a PR: #14.
